---
abstract: 'Unofficial Jawbone UP API'
author:
  - 'Alan Berndt <alan@eatabrick.org>'
build_requires:
  Test::Approx: 0
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.035
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Jawbone-Up
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Carp: 0
  DateTime: 0
  JSON: 2.0
  LWP::UserAgent: 0
  perl: 5.010
resources:
  bugtracker: https://github.com/bentglasstube/WWW-Jawbone-Up/issues
  homepage: https://github.com/bentglasstube/WWW-Jawbone-Up
  repository: https://github.com/bentglasstube/WWW-Jawbone-Up.git
version: 1.32.3
